elebotate directory Structure and perform specific task
sonukumar-a11/AssignmentRust pull request #7
Opened 2021-03-10 11:57 UTC by sonukumar-a11

Any additional information for the reviewer to start
NA

How should this be manually tested?
We need window OS in which Rust is installed. then execute this rust program

Which Trello task and sub-task does this change relate to?

Are there any changes pending?
No
Does any team have to be notified of changes in this feature?
Yes
Definition of Done:
Is there >80% unit test code coverage?
Yes
if not please mention the Code Coverage of code.
Does this PR add new dependencies? If so, please list out the same.
Will this feature require a new piece of infrastructure to be implemented?
Is there appropriate logging included?
Does the project compile ok?
Yes
Have Clippy violations been fixed?
Yes
 Have Code is properly formatted?
Yes

2021-03-11 10:03 UTC, aman09v commented on Assignments/assignment7/src/string_manipulation.rs
> +    while i < iterator2.len() {
use meaning full names 
do not use 'i'

2021-03-11 10:03 UTC, aman09v commented on Assignments/assignment7/src/task/generating_subset.rs
> +    for i in 0..input_iterable.len() {
do not use i, j

2021-03-11 10:04 UTC, aman09v requested changes
changes suggested

2021-03-11 10:12 UTC, aman09v commented on Assignments/assignment7/src/string_manipulation.rs
> +/// This function take input to as
use meaningful comments

2021-03-11 10:12 UTC, aman09v requested changes
use good comments

2021-03-11 21:29 UTC, closed without merging

2021-03-11 21:29 UTC, sonukumar-a11 commented
Nothing

2021-03-12 16:55 UTC, sonukumar-a11 commented
Nothing